TextWidget:


<TextWidget>:
  BoxLayout:
    orientation: "vertical"
    size: root.size
  
    Label:
      id: label1
      font_size: 70
      text: root.text

    BoxLayout:
      TextInput:
        id: text_box
        size_hint_x: 70
        font_size: 70
        focus: True
        on_text_validate: root.buttonClicked()
      
      Button:
        id: button1
        size_hint_x: 30
        text: "OK"
        font_size: 70
        on_press: root.buttonClicked()
